"use server";

import { createAdminClient } from "@/lib/supabase/admin";
import type { OrderStatus } from "@/lib/constants";

interface CreateOrderInput {
  full_name: string;
  email: string;
  phone: string;
  cedula: string;
  address: {
    street: string;
    city: string;
    state: string;
    zip?: string;
    reference?: string;
  };
  payment_method: "pago_movil" | "transferencia" | "zelle";
  notes?: string;
  reference_number: string;
  declared_amount: number;
  items: {
    variant_id: string;
    quantity: number;
  }[];
}

interface CreateOrderResult {
  success: boolean;
  order_number?: string;
  error?: string;
}

export async function createOrder(
  input: CreateOrderInput
): Promise<CreateOrderResult> {
  const supabase = createAdminClient();

  try {
    // 1. Get current exchange rate
    const { data: rate, error: rateError } = await supabase
      .from("exchange_rates")
      .select("*")
      .eq("is_current", true)
      .single();

    if (rateError || !rate) {
      return { success: false, error: "No hay tasa de cambio configurada" };
    }

    // 2. Validate stock and calculate totals
    let subtotalUsd = 0;
    const orderItems: {
      variant_id: string;
      product_name: string;
      variant_desc: string;
      quantity: number;
      unit_price_usd: number;
      subtotal_usd: number;
    }[] = [];

    for (const item of input.items) {
      const { data: variant } = await supabase
        .from("product_variants")
        .select("*, product:products(name, base_price_usd)")
        .eq("id", item.variant_id)
        .single();

      if (!variant || variant.stock < item.quantity) {
        return {
          success: false,
          error: `Stock insuficiente para ${variant?.product?.name ?? "producto"}`,
        };
      }

      const unitPrice = variant.price_override_usd ?? variant.product?.base_price_usd ?? 0;
      const itemSubtotal = unitPrice * item.quantity;
      subtotalUsd += itemSubtotal;

      orderItems.push({
        variant_id: item.variant_id,
        product_name: variant.product?.name ?? "",
        variant_desc: `${variant.color} / ${variant.size}`,
        quantity: item.quantity,
        unit_price_usd: unitPrice,
        subtotal_usd: itemSubtotal,
      });
    }

    const totalUsd = subtotalUsd;
    const totalBs = totalUsd * rate.rate_bs_per_usd;

    // 3. Create or update customer
    const { data: existingCustomer } = await supabase
      .from("customers")
      .select("id")
      .eq("email", input.email)
      .single();

    let customerId: string;

    if (existingCustomer) {
      customerId = existingCustomer.id;
      await supabase
        .from("customers")
        .update({
          full_name: input.full_name,
          phone: input.phone,
          cedula: input.cedula,
          address: input.address,
          state: input.address.state,
        })
        .eq("id", customerId);
    } else {
      const { data: newCustomer, error: custError } = await supabase
        .from("customers")
        .insert({
          email: input.email,
          full_name: input.full_name,
          phone: input.phone,
          cedula: input.cedula,
          address: input.address,
          state: input.address.state,
        })
        .select("id")
        .single();

      if (custError || !newCustomer) {
        return { success: false, error: "Error al crear cliente" };
      }
      customerId = newCustomer.id;
    }

    // 4. Create order (order_number is auto-generated by trigger)
    const { data: order, error: orderError } = await supabase
      .from("orders")
      .insert({
        order_number: "TEMP", // Will be overwritten by trigger
        customer_id: customerId,
        payment_method: input.payment_method,
        subtotal_usd: subtotalUsd,
        exchange_rate_id: rate.id,
        exchange_rate_snapshot: rate.rate_bs_per_usd,
        total_usd: totalUsd,
        total_bs: totalBs,
        shipping_address: input.address,
        notes: input.notes ?? null,
      })
      .select("id, order_number")
      .single();

    if (orderError || !order) {
      console.error("Order creation error:", orderError);
      return { success: false, error: "Error al crear pedido" };
    }

    // 5. Create order items
    const { error: itemsError } = await supabase
      .from("order_items")
      .insert(
        orderItems.map((item) => ({
          order_id: order.id,
          ...item,
        }))
      );

    if (itemsError) {
      console.error("Order items error:", itemsError);
    }

    // 6. Create payment proof
    const declaredCurrency = input.payment_method === "zelle" ? "USD" : "VES";
    await supabase.from("payment_proofs").insert({
      order_id: order.id,
      image_url: "pending-upload", // TODO: Handle file upload to Storage
      reference_number: input.reference_number,
      declared_amount: input.declared_amount,
      declared_currency: declaredCurrency,
    });

    return { success: true, order_number: order.order_number };
  } catch (error) {
    console.error("Error creating order:", error);
    return { success: false, error: "Error al procesar tu pedido" };
  }
}

export async function getOrderByNumber(
  orderNumber: string,
  email: string
): Promise<{
  order: {
    order_number: string;
    status: OrderStatus;
    payment_method: string;
    total_usd: number;
    total_bs: number;
    created_at: string;
    items: { product_name: string; variant_desc: string; quantity: number; unit_price_usd: number }[];
    shipment?: { carrier: string; tracking_number: string; tracking_url?: string; status: string };
  } | null;
  error?: string;
}> {
  const supabase = createAdminClient();

  // Verify email matches the order's customer
  const { data: order, error } = await supabase
    .from("orders")
    .select(`
      *,
      customer:customers!inner(email),
      items:order_items(*),
      shipments(*)
    `)
    .eq("order_number", orderNumber)
    .eq("customer.email", email)
    .single();

  if (error || !order) {
    return { order: null, error: "Pedido no encontrado. Verifica el número y email." };
  }

  return {
    order: {
      order_number: order.order_number,
      status: order.status,
      payment_method: order.payment_method,
      total_usd: order.total_usd,
      total_bs: order.total_bs,
      created_at: order.created_at,
      items: order.items ?? [],
      shipment: order.shipments?.[0] ?? undefined,
    },
  };
}
